title: Simple Page
preset: page

icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

pages:
  template: default

fields:
  text:
    type: textarea
    size: huge
